# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: '.bumpversion.cfg'
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args:
          - --ignore
          - B6
          - --msg-filename
        stages: [ commit-msg ]
  - repo: https://github.com/crate-ci/typos
    rev: v1.29.9
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.7
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args:
          - --strict
        additional_dependencies:
          - 'click>=8.1.8,<9.0'
          - 'easyocr>=1.7.2,<2.0'
          - 'hypothesis>=6.125.2,<7.0'
          - 'pytest>=8.3.4,<9.0'
          - 'telethon>=1.38.1,<2.0'
          - 'tomli>=2.2.1,<3.0'
          - 'types-setuptools'
          - 'typing_extensions>=4.12.2,<5.0'
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.394
    hooks:
      - id: pyright
        additional_dependencies:
          - 'click>=8.1.8,<9.0'
          - 'easyocr>=1.7.2,<2.0'
          - 'hypothesis>=6.125.2,<7.0'
          - 'pytest>=8.3.4,<9.0'
          - 'telethon>=1.38.1,<2.0'
          - 'tomli>=2.2.1,<3.0'
          - 'types-setuptools'
          - 'typing_extensions>=4.12.2,<5.0'
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
