[telegram]
api_id = 12345 # get your own `api_id` from https://my.telegram.org/apps
api_hash = "1234567890abcdef1234567890abcdef" # get your own `api_hash` from https://my.telegram.org/apps
peers = [
    "me",
    "durov",
    777000,
    -1001006503122,
]
